### ISSUE TITLE
UI and UX testing 

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#33]
The whole application needs **detailed** user testing, which means checking every button, form field, different scenarios of actions
# TO BE defined in details

- [ ] Testing as the librarian
    
- [ ] Testing as a patron

continue on : https://github.com/inveniosoftware/react-invenio-app-ils/pull/240

**Comment by FlorianCassayre** [comment]
After discussion we concluded it would be nice to automate the testing process, instead of manually executing the scenario and verifying the outcome. One such tool, [`cypress`](https://www.cypress.io/), allows to write test cases with a similar syntax to `mocha` (describe, it, expect, ...) while providing tools to interact with the UI (visit, type, click, ...). One advantage is that we can directly connect it to our backend, however we must ensure that the backend holds the same data over all the executions. Therefore it is not possible to use the demo data as is because it is based on randomness (and setting a seed is not a good solution because it would break completely on schema change).

Instead of defining a lot of static data in the backend, we could start with a minimal dataset that allows the site to work (demo users and roles) and then construct the further data we need using the frontend testing tool. It would make it easier to maintain since most of the test data would be located at the same place.

**Comment by FlorianCassayre** [comment]
Linking [this comment](https://github.com/inveniosoftware/react-invenio-app-ils/pull/240#issuecomment-710424890).
