### ISSUE TITLE
Data integrity (more) issues

### ISSUE THREAD

**Issue by neilharrisbrown** [inveniosoftware/react-invenio-app-ils#400]
Package version (if known): Latest (29)

## Describe the bug
Further testing the search kit, found additional data issues related to #399. I am listing two of these issues below. Likely there are others.

## Steps to Reproduce
1. Do all steps per #399 
2. Then go to the Book details page for "Intro to cryptography" book
3. You will see under "Physical Items" the two items, but with Loan status incorrectly showing only "-" for the checked out item also (77...305)

4. Then go to Loans search and find another pending Loan request for "cryptography" - select the one for a different user Medrod
5.  Go to the Loan details page and here you'll find under "Available Items", the same item that was previously checked out with button to "checkout" enabled. Although it gives error msg when clicked, it seems to me,  should not be showing it in the first place.

## Expected behavior
For step 3, Loan status should properly show one of the items "on Loan"
For step 5, it seems the Available items should not show this item since it was already checked out by another user Devi.

## Additional context
It seems these errors are due to the checkout update not being reflected elsewhere in the rest of the app. But it seems to show the checkout in the Item Details page correctly as "Item on Loan". You may please investigate it further.

**Comment by neilharrisbrown** [comment]
Loan search correctly shows item already on loan to user Devi (per checkout in #399 

Now select another Pending from user Medrod



<img width="920" alt="LoanSearch" src="https://user-images.githubusercontent.com/80505283/110911933-2faeff80-82c8-11eb-8025-64dee7868cbe.png">

**Comment by neilharrisbrown** [comment]
Here is the Step 5 error - why is "Available" showing this item for "checkout" - it was previously checked out in #399 ?



<img width="920" alt="co-2" src="https://user-images.githubusercontent.com/80505283/110912191-7dc40300-82c8-11eb-8b0c-486736185fcd.png">

**Comment by neilharrisbrown** [comment]
In the above search screen, why is Availability showing 5? It did not change after starting celery. The only physical copy that was CAN_CIRCULATE was checked out already. So, Available is 0 unless it means something else altogether?

Another important thing that comes to mind in this context is if celery or the message broker fails silently (such as a software crash not recoverable with failover), there should be a failsafe mechanism to prevent bad (stale) data from being presented (for example the Available physical copies with "checkout" above). In this case, it was caught by downstream validation, but unless there is a check for every possible state transition in all user functionality, it could lead to unintended consequences and possibly corrupted state.

**Comment by ntarocco** [comment]
I just tested if and for me everything works fine. Here my step:

1. Search for the keyword in Physical Copies:
![Screenshot 2021-03-15 at 15 56 41](https://user-images.githubusercontent.com/2089455/111174248-9291e680-85a7-11eb-8afd-12f2bda43d13.png)

2. Checked in the document if there were indeed 2:
![Screenshot 2021-03-15 at 15 56 54](https://user-images.githubusercontent.com/2089455/111174313-a0476c00-85a7-11eb-8851-4f5eed8445b9.png)

3. I checked out one of the copy for one user

4. I go to the same and I can only "checkin/extend/cancel" and I have no actions in the others:
![Screenshot 2021-03-15 at 15 59 48](https://user-images.githubusercontent.com/2089455/111174562-d08f0a80-85a7-11eb-8a65-15507905f2ad.png)

My feeling is that celery was not running again.
The UI heavily relies on the stated of other records indeed and performs many searches, but the main validation is done backend side. The backend, most of the time, is relying on DB state, but in some cases it also performs searches.
Let's take this example that you can try yourself:
1. Stop celery
2. Go go the document `Big Bang (ed. 3x - 2019)`, it should have multiple Physical copies (or find/create another with multiple)
3. Checkout a copy for a patron: the checkout will create a loan and will perform a reindex of the loan in Elasticsearch synchronously: if it fails, the request fails.
4. Now, if you come back to the document, indeed the status of the Physical copies is not updated and you still see "-" in the status. If you try to checkout that copy to another patron, the request will fail because is already on loan.

Just to complete: Elasticsearch is considered in Invenio as a reliable source, as a DB and it should be always be up-to-date. For the critical operations, in InvenioILS we try to use the database (not ES) as source of through.
In any case, you will have to setup logging when exceptions are raised (we use Sentry), there should be no "silent fails" as you said.

**Comment by neilharrisbrown** [comment]
Yes, I think celery seems to fail occasionally and causes problems and monitoring software is a good idea. Here are a couple of error logs from my screen. I was just reporting what I encountered based on a quick test run. You may close the issue.

--------
[2021-03-15 03:18:16,947: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: Server unexpectedly closed connection.
Trying again in 2.00 seconds... (1/100)

[2021-03-15 03:18:18,961: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: Server unexpectedly closed connection.
Trying again in 4.00 seconds... (2/100)

-------
Separate error/warning:
[2021-03-15 05:49:53,119: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
