### ISSUE TITLE
Loans Date search broken

### ISSUE THREAD

**Issue by neilharrisbrown** [inveniosoftware/react-invenio-app-ils#404]
Package version (if known): 29

## Describe the bug
Loans Date search doesn't work properly

## Steps to Reproduce
There are multiple issues:
1. In Loans search page, the date filter currently allows only one field (From or To) to be entered, 
2. Clicking on x doesn't clear the field and typing keyboard DELETE key doesn't clear it - only works sometimes 
3. The results are erratic - see screenshot

**Comment by neilharrisbrown** [comment]
From date - 3/9/21, but results show older start dates


<img width="1022" alt="Date" src="https://user-images.githubusercontent.com/80505283/111075203-1498e700-84a4-11eb-8d4b-810410f0a190.png">

**Comment by KonstantinaStoikou** [comment]
Thank you for reporting those bugs. The first 2 bugs will be fixed by this [PR](https://github.com/inveniosoftware/react-invenio-app-ils/pull/419). The 3rd bug (the one in the screenshot) I tested it and it looks to be working fine. Could you maybe provide more information about which browser you were using and if you following any specific steps to reproduce it?

**Comment by neilharrisbrown** [comment]
Got those results from the date query per the screen shot, but as mentioned it was erratic i.e. with both seemingly correct and incorrect results at times. If you've tested and cannot reproduce, you may close the issue. I am not able to test it again. Thanks.
